# Generated by Django 3.2.3 on 2023-12-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='título',
            new_name='titulo',
        ),
    ]
